apiVersion: v1
kind: ConfigMap
metadata:
  name: terraria-config
  namespace: default
data:
  worldname: "{{worldName}}"
  maxplayers: "{{maxPlayers}}"
  difficulty: "{{difficulty}}"
  autocreate: "{{worldSize}}"
  password: "{{password}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
  namespace: default
  labels:
    app: terraria
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      containers:
        - name: terraria
          image: hexlo/terraria-server-docker:latest
          ports:
            - containerPort: 7777
              protocol: TCP
          env:
            - name: world
              value: "/root/.local/share/Terraria/Worlds/{{worldName}}.wld"
            - name: worldname
              valueFrom:
                configMapKeyRef:
                  name: terraria-config
                  key: worldname
            - name: autocreate
              valueFrom:
                configMapKeyRef:
                  name: terraria-config
                  key: autocreate
            - name: maxplayers
              valueFrom:
                configMapKeyRef:
                  name: terraria-config
                  key: maxplayers
            - name: difficulty
              valueFrom:
                configMapKeyRef:
                  name: terraria-config
                  key: difficulty
            - name: password
              valueFrom:
                configMapKeyRef:
                  name: terraria-config
                  key: password
            - name: secure
              value: "0"
          stdin: true
          tty: true
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: worlds
              mountPath: /root/.local/share/Terraria/Worlds
      volumes:
        - name: worlds
          hostPath:
            path: "{{worldsPath}}"
            type: DirectoryOrCreate
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: terraria
  namespace: default
spec:
  type: NodePort
  selector:
    app: terraria
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
